# Generated by Django 5.2 on 2025-04-12 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtomodel',
            name='imagem',
            field=models.ImageField(default='', upload_to='imagensProdutos'),
        ),
    ]
