# Generated by Django 5.2 on 2025-04-12 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_produtomodel_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtomodel',
            name='preco',
            field=models.FloatField(default=10.0, max_length=255),
        ),
    ]
