# Generated by Django 5.2 on 2025-04-12 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_alter_produtomodel_avalicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtomodel',
            name='imagem',
            field=models.ImageField(upload_to='imagensProdutos'),
        ),
    ]
