# Generated by Django 5.2 on 2025-04-12 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0006_alter_produtomodel_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtomodel',
            name='avalicao',
        ),
        migrations.AddField(
            model_name='produtomodel',
            name='avaliacao',
            field=models.IntegerField(default=1),
        ),
    ]
